### PR TITLE
Add option to disable IPv4.

### PR DESCRIPTION
**Pull request by thack1**
Add an option to disable updating A records for a domain. This is relevant for ISPs that only provide public IPv6 addresses.

### CODE REVIEW

**Comment by Hentra** [comment]
This is a nice addition and I see why that is a requirement for some users.

There is one thing that might be dangerous: With that the user now has the possibility to disable both IPv4 and IPv6 address update when the IPv4 field is not present in the configuration. This will be the case for most people that upgrade to the next version. We will need a notification to the user that the configuration is invalid when both IPv4 and IPv6 are set to false. I will see and check if I can implement that.

**Comment by thack1** [comment]
You are right. So maybe the IPv4 option should be enabled by default if it is missing in the config file. Then there would be no problems when people update. What do you think?

**Comment by Hentra** [comment]
That sounds like a reasonable way of solving that issue! I will be working on it today.

**Comment by thack1** [comment]
Thanks!

**Pull request merged**
